<?php

namespace AccopopBundle\Repository;

/**
 * aroundvehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aroundvehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
