<?php

namespace AccopopBundle\Repository;

/**
 * invehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class invehiculeRepository extends \Doctrine\ORM\EntityRepository
{
}
